# Global metadata for the SATM Engineering website.
siteDescription = "SATM Engineering builds resilient systems, infrastructure, and tooling for modern teams."
primaryColor = "#0a84ff"
secondaryColor = "#0b1f3a"

[logo]
  text = "SATM"
  tagline = "Engineering"

[social]
  github = "https://github.com/satm-engineering"
  linkedin = "https://www.linkedin.com/company/satm-engineering/"
  twitter = "https://x.com/satm_eng"
  email = "hello@satm.engineering"

[hero]
  title = "Systems Automation & Technical Mastery"
  subtitle = "SATM Engineering partners with product and platform teams to deliver secure, automated infrastructure and resilient cloud-native applications."
  primaryButtonText = "Engage with us"
  primaryButtonLink = "/contact/"
  secondaryButtonText = "View capabilities"
  secondaryButtonLink = "/services/"

[about]
  title = "Pragmatic, measurable engineering outcomes"
  body = [
    "We bring deep experience in observability, developer experience, and infrastructure automation to accelerate your roadmap.",
    "Our engineers embed with your teams to ship reliable products while upskilling your organization for long-term success."
  ]
  highlight = "Trusted by product leaders across fintech, logistics, and SaaS."

[cta]
  title = "Ready to transform your engineering operations?"
  description = "Let's design a delivery platform that unlocks your roadmap."
  buttonText = "Book a discovery call"
  buttonLink = "mailto:hello@satm.engineering"

[[values]]
  title = "Accelerated Delivery"
  icon = "fas fa-rocket"
  description = "Modern pipelines and platform automation bring features to production faster with confidence."

[[values]]
  title = "Operational Excellence"
  icon = "fas fa-shield-alt"
  description = "Resilience, observability, and proactive reliability engineering keep customer experiences stable."

[[values]]
  title = "Team Enablement"
  icon = "fas fa-users-cog"
  description = "Coaching and knowledge transfer unlock sustainable velocity for your product and platform teams."

[[services]]
  title = "Platform Engineering"
  summary = "Design and build paved roads tailored to your developers with platform product thinking."

[[services]]
  title = "Cloud Infrastructure"
  summary = "Secure multi-cloud environments with Terraform, Kubernetes, and policy-driven governance."

[[services]]
  title = "Observability & SRE"
  summary = "Implement telemetry, alerting, and operational runbooks that keep teams focused on outcomes."

[[services]]
  title = "DevSecOps Automation"
  summary = "Embed compliance and security automation early in the delivery lifecycle."

[[testimonials]]
  quote = "SATM Engineering helped us launch a self-service platform with confidence and observability baked in."
  client = "Director of Engineering, SaaS Platform"

[[testimonials]]
  quote = "Their platform engineers worked as part of our team, leaving us with both the systems and the skills to operate them."
  client = "VP Technology, Logistics Startup"

[footer]
  copyright = "© "
  company = "SATM Engineering"
  copyYear = 2025
