name = "Hugoplate"
author = "SATM Engineering"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Vendored snapshot of the Hugoplate theme tailored for SATM Engineering."
homepage = "https://satm.engineering"
